version: 2.1

npm-steps: &npm-steps
  docker:
    - image: cimg/node:13.8.0
  steps:
    - checkout

jobs:
  build:
    <<: *npm-steps
    steps:
      - run: npm i
      - save_cache:
          key: "npm-packages"
          paths:
            - /src/node_modules
      - run: npm run lint
  test:
    <<: *npm-steps
    steps:
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm i
      - run: npm run test
  analyze:
    <<: *npm-steps
    steps:
      - run: npm audit
workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
